### ISSUE TITLE
move to Grattan shinyapps.io account

### ISSUE THREAD

**Issue by MattCowgill** [grattan/macrodashboard#8]
there's no rush, but at some point it would be good to move this to the Grattan shinyapps.io account. 

Steps: 

1. Get a Grattan shinyapps.io token + secret from the account admin (@jamesha95)
2. On your local machine, with `macrodashboard` as your active project, run `setAccountInfo(name='grattan', token=[TOKEN], secret=[SECRET])` then `rsconnect::deployApp(appName = 'macrodashboard')`
3. Edit the GitHub Secrets for this repo (Settings -> Secrets in this GitHub Repo), replacing `SHINYAPPS_TOKEN` and `SHINYAPPS_SECRET` with the values you got from James. 
4. Edit this file and commit to master: https://github.com/grattan/macrodashboard/blob/master/.github/workflows/deploy-shiny.yaml. Replace `name='mattcowgill'` with `name='grattan'`. 

That should do it.

**Comment by wfmackey** [comment]
Moved to Grattan shiny apps account now 🤙

**Comment by MattCowgill** [comment]
:sickkkk:
